### ISSUE TITLE
v2: Firmware available?

### ISSUE THREAD

**Issue by kruton** [feedernet/petnet-feeder-service#12]
It would be good to have a binary of the firmware that the device uses. The board has two unpopulated JTAG headers along with a [Silex Technology SX-ULPGN](https://www.silextechnology.com/hubfs/Resource%20PDF/137-00211-100C%20SX-ULPGN%20Product%20Specification.pdf) chip and a [RIGADO BMD-300](https://www.u-blox.com/sites/default/files/BMD-300_DataSheet_%28UBX-19033350%29.pdf) chip.

The SX-ULPGN supports a serial debug UART on pins 38 and 39. The BMD-300 allows SWD read back of the firmware (the version in the Petnet Feeder 2.0 is the AD version that is not locked).

**Comment by kruton** [comment]
I connected a serial console to the SX-ULPGN and it outputs the following. It resets every 30 seconds or so:
```
reset cause:RESET_1
_WAKEMGR_Register  item:0x43a558
cmnos_allocram_init: start=0x44eaf0 size=725064
NUM_DEV=2 FWMODE=5 FWSUBMODE=0 FWBR_BUF 1
Mac address is : [removed]
wlan power patch
_WAKEMGR_Register  item:0x43e194
RegDB opened
AMSDU enabled
WNM INIT
_WAKEMGR_Register  item:0x467230
_WAKEMGR_Register  item:0x469f38
alloc rem: 593068
host_dset_init
_host_dset_do_init
ram_dset_init
otp_dset_init
rom_dset_init
mem_dset_init
DataSet asynchronous initialization done (0)
```

**Comment by kruton** [comment]
I bought a little [SWD device](https://www.amazon.com/CJMCU-FT232H-High-Speed-Multifunction-Module/dp/B077W76L7C) from Amazon and connected it to the BMD-300 SWD connector (J101) on the main board. I used OpenOCD to dump the firmware contents to inspect with Ghidra.

![Screenshot from 2020-10-03 16-52-46](https://user-images.githubusercontent.com/50407/95003930-9998df80-0599-11eb-81aa-f0ff6d189cd2.png)

**Comment by kruton** [comment]
Here's a list of the API calls I could see:
```
/api/v1/kronos/software/releases/transactions/
/api/v1/core/events
/api/v1/kronos/software/releases/transactions
/api/v1/kronos/software/releases/transactions/%s/received
/api/v1/kronos/software/releases/transactions/%s/succeeded
/api/v1/kronos/software/releases/transactions/%s/failed
/api/v1/kronos/devices
/api/v1/kronos/gateways
```
These look like possible JSON API fields:
```
_|deviceHid
s|local_md5
s|msg_type
sensor
f|voltage
i|usb
i|chg
i|rssi
i|btn
i|mem
s|pnid
s|fw_ver
s|wifi
s|log
feed_result
s|s_id
s|s_p
s|s_act
s|s_auto
s|s_r
s|s_t
i|stime
i|etime
f|e_g
f|a_g
f|h_s
f|h_e
i|src
b|fail
s|err
s|rid
b|online
s|remote_md5
```
```

**Comment by kruton** [comment]
Here are my notes from looking at the handlers for messages via MQTT:

Outgoing message types (6 total):

Topic = "`krs.tel.gts.<clientId>`"

- 0 - boot
- 1 - sensor 
`{"_|deviceHid":"ad06c3b579d59b2045fe01c37d18ca7252336935","s|msg_type":"sensor","f|voltage":4086,"i|usb":1,"i|chg":0,"i|ir":1,"i|rssi":99,"i|btn":1,"i|mem":5648}`
- 2 - feed_result
`{"_|deviceHid":"ad06c3b579d59b2045fe01c37d18ca7252336935","s|msg_type":"feed_result","i|stime":1601883341,"i|etime":1601883343,"f|e_g":27,"f|a_g":0,"f|h_s":-133,"f|h_e":-133,"i|src":5,"b|fail":true,"s|err":"Unknown Error","s|rid":""}`
- 3 - hb (heartbeat)
`{"_|deviceHid":"ad06c3b579d59b2045fe01c37d18ca7252336935","s|msg_type":"hb","b|online":1}`
4 - trace (debug trace)
`{"_|deviceHid":"ad06c3b579d59b2045fe01c37d18ca7252336935","s|msg_type":"trace","i|tl":32,"s|ts":"Start - D�, Portion: 0 tbsp(309448g), Turns: 41, Bowl: 0g, Hopp"}`
`{"_|deviceHid":"ad06c3b579d59b2045fe01c37d18ca7252336935","s|msg_type":"trace","i|tl":32,"s|ts":"Results - Actual: 536928072 tbsp(0g), End: 309476, Bowl: 44g Ho"}`
5 - hash
`{"_|deviceHid":"ad06c3b579d59b2045fe01c37d18ca7252336935","s|local_md5":"9f12737513eebebdfa70ca72fa562c45","s|msg_type":"hash","s|remote_md5":"26a98b0dc2ae400c65711957f5a14d5a"}`

Incoming message type:

- reboot
- feed
 - portion (tablespoons?)
Possible other incoming messages (not sure what the actual commands are):
- button_enable_remote
- schedule ??
 - active
 - automatic
 - feeding_id
 - reminder

Test data from firmware?	`[{"active":true,"automatic":true,"feeding_id":"40006b28dbdfd7b2_zbxM2a_11:46AM","name":"FEED2","portion":0.0625,"reminder":false,"time":%ld}]`
 
- budget ??
 - tbsp_per_feeding
 - recipe
 - g_per_tbsp
 - budget_tbsp
 
 Test data in firmware:
 `{"budget_cups":0.75,"cups_per_feeding":0.25,"kcals_per_cup":519,"kcals_per_day":389.75,"kg_per_cup":0.10421836228287841,"managed":false,"num_feedings":3,"recipe":"E0000060"}`
 
- utc ?? (maybe:utc_offset)
 - utc_offset

**Comment by tedder** [comment]
ohhhhhh, so I was seeing the first three API interactions and it was then appearing dead. That's because it flipped to MQTT?

great work. lemme get you on Slack, though it's quiet.. I've been waiting for someone to make forward progress.

**Comment by kruton** [comment]
I started back up the MQTT server and got it to try to dispense. My hopper is empty so it spun for probably 20 seconds fruitlessly. I'm not sure what the portion measurements mean yet.

You have to look at what topic it subscribes to. My PetNet is subscribing using the client ID `40285608b03f085d1b4e31ec5f60b3b912f64f2d` and `deviceHid` of `ad06c3b579d59b2045fe01c37d18ca7252336935` in the example below.
```
hbmqtt_pub --url mqtt://localhost:1883/ -t 'krs/cmd/stg/40285608b03f085d1b4e31ec5f60b3b912f64f2d' -m '{"hid":"feed1","name":"SendCommand","encrypted":false,"parameters":{"deviceHid":"ad06c3b579d59b2045fe01c37d18ca7252336935","command":"feed","payload":"{\"portion\":2}"}}'
```
The feeder will send an HTTP-via-MQTT response to topic `krs.api.gts.40285608b03f085d1b4e31ec5f60b3b912f64f2d` of something like:
```
{"requestId":"GS-2020-10-06T00:18:47.000Z","eventName":"GatewayToServer_ApiRequest","encrypted":false,"parameters":{"uri":"/api/v1/core/events/feed1/received","method":"PUT","apiKey":"efa2396b6f0bae3cc5fe5ef34829d60d91b96a625e55afabcea0e674f1a7ac43","apiRequestSignature":"dc6ba210d41c72ae2997e1c7ddcdb36316e55356061fa09c30db558c1279a330","apiRequestSignatureVersion":"1","timestamp":"2020-10-06T00:18:46.000Z"},"signature":"8198cf30c1a98972d238680fe92798d3124dfa66653f58a6f2d607935330a564","sign
atureVersion":"1"}')}                                                                                  
```

You must respond to the `requestId` (in this example `GS-2020-10-06T00:18:47.000Z`) with a HTTP 200 OK equivalent status before it will proceed:
```
hbmqtt_pub --url mqtt://localhost:1883/ -t 'krs/api/stg/40285608b03f085d1b4e31ec5f60b3b912f64f2d' -m '{"requestId":"GS-2020-10-06T00:18:47.000Z","eventName":"GatewayToServer_ApiRequest","encrypted":false,"parameters":{"status":"OK"}}'
```

**Comment by fbretmounet** [comment]
@kruton , I'm trying to replicate your findings on a first generation feeder. If I followed you correctly, point mqtt-a01.arrowconnect.io to a machine on your local network (I use pihole and love it!). Start a mosquitto broker on that machine and the feeder should start publishing messages to that broker?
If so, I've spent some time on it and it seems gen 1 is not mqtt-aware :-(

**Comment by tedder** [comment]
Everything about the gen1 is different, Fred. Seriously, no hardware or software or APIs are common to them (afaict).

**Comment by kruton** [comment]
@fbretmounet do you have any pictures of the electronics on the V1 feeder? It seemed like all the smarts may have been in the bowl.

**Comment by fbretmounet** [comment]
@kruton , yes it is under the bowl. I took the attached pictures when I opened it a few weeks ago. Let me know if you want more pictures!
![20200821_160622](https://user-images.githubusercontent.com/35351212/95364965-58008100-0886-11eb-893b-7f1b311cc625.jpg)
![20200821_155438](https://user-images.githubusercontent.com/35351212/95364982-5d5dcb80-0886-11eb-8fee-e8a621a7d5ff.jpg)

**Comment by kruton** [comment]
Looks like this might be a design based on [electricimp imp003](https://developer.electricimp.com/hardware/imp/imp003_hardware_guide). Are there any pictures of the overall board? I'd be more interested to see if there are [pads to connect debug cables](https://developer.electricimp.com/resources/disconnecteddebugging) as mentioned in their documentation.

**Comment by fbretmounet** [comment]
Here are picture of the top of the board and a picture of the back only showing test pads. I did not find obvious jtag or serial pads. I did not find standard debug documentation from electricimp. :-(
https://developer.electricimp.com/hardware/imp/imp003pinmux suggests quite a few different combinations for serial... I guess I could try every one of them...

![20201007_105930](https://user-images.githubusercontent.com/35351212/95372013-d3b2fb80-088f-11eb-9452-674a1d7d828e.jpg)
![20201007_105937](https://user-images.githubusercontent.com/35351212/95372031-d877af80-088f-11eb-9420-07e2ad53fa40.jpg)
![20201007_110025](https://user-images.githubusercontent.com/35351212/95372037-d9104600-088f-11eb-8262-7206d48e801a.jpg)

**Comment by tedder** [comment]
When the gen1 discussion came up in the past, it sounded like the Imp was shipped in "production mode", locking down a lot of the debugging and such.

**Comment by fbretmounet** [comment]
I hate it when manufacturers do it right! The alternative is to rebuild my own board :-(

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kruton** [comment]
You could order a V2 on Amazon for $65 :)

**Comment by brbeaird** [comment]
Such a bummer. You guys are doing great work - hate that I can't easily
apply this to my V1. Honestly hate the idea of just chucking the whole
thing into the trash, but I don't know what else I'd do with it. I already
bought a PetKit feeder, which seems to do the job just as well.

**Comment by SixthTitan** [comment]
Couldn't you reverse engineer the petnet android app to point to a url
you've constructed with mqt? I assume there might be a variable in there
somewhere that points to these endpoints.

**Comment by kruton** [comment]
I don't know what the V1 looks like on the network. I would suggest trying to do packet captures of what it's sending across the network (or trying to send now that PetNet's domains are defunct).

**Comment by wnhanna** [comment]
>  I already bought a PetKit feeder, which seems to do the job just as well.
> […](#)
Gen1 guy here, new to the thread. I JUST bought a PetSafe unit from eBay last night to replace our feeder. I see this comment and look it up, looks like exactly what I want - Bluetooth to program if their servers disappear being a big draw. Oh well.

**Comment by tedder** [comment]
Hey gen1 folks, this is hard to thread, please go into #15 to work on efforts there. @fbretmounet can you repost your images and text there? I'm going to delete the messages from this thread.

**Comment by ak48disk** [comment]
There's a 8Mbit flash chip on my 2.0 device board that I can read through a programmer. It seems contains some firmware and it disassembles as a ARM binary. 

However, I didn't put much effort in the firmware but I just replaced the main board with a resperberry pi to just drive the motor from time to time. I lost all the weight sensors and motion sensors, but it's the quickest way that I can get my feeder back to work.

**Comment by mbillow** [comment]
Closing this out since we have pretty much everything working with the V2 feeders.

**Comment by hassankhan** [comment]
Hi @kruton :wave:

Any chance you could post the firmware image?
