### ISSUE TITLE
Any way we can help?

### ISSUE THREAD

**Issue by brbeaird** [feedernet/petnet-feeder-service#3]
Let me know if I can help here in some way - hard to tell just be reading the code what your thoughts are.

**Comment by tedder** [comment]
I'll add a readme and try to organize, but email me at ted@timmons.me and I'll send you a slack invite.

**Comment by mmase** [comment]
also want to help, if this project isn't abandoned.

**Comment by guigarfr** [comment]
@tedder is the project abandoned?

**Comment by brbeaird** [comment]
I think the company is dead for good this time. Went down before people could get a good chance to fully reverse-engineer things.

**Comment by tedder** [comment]
I've pointed a couple of people at this github issue. More than happy to interact if anyone has ideas of how to advance it, and I can start re-inviting people to the Slack channel. But unless people are willing to roll their sleeves up, I'm out of energy to explore it. The code in here works on the first three requests from the feeder but presumably that third payload response is wrong.

**Comment by tedder** [comment]
There's a functional hack, please help modify the README and do anything else you can.

**Comment by mbillow** [comment]
Closing this out since the project has made leaps and bounds of progress since this ticket was opened and I don't feel it is useful to have open anymore nor is it about anything specific.
