### ISSUE TITLE
Mobile App Reverse Engineering

### ISSUE THREAD

**Issue by dcmeglio** [feedernet/petnet-feeder-service#5]
I know you said it's secondary, but I did a lot of reverse engineering on their mobile app which relies mostly on Firebase. If you look at my source code https://github.com/dcmeglio/hubitat-petnet you'll see some info that could be useful. Figured I'd share in case it helps

**Comment by tedder** [comment]
oh wow, that is super helpful! very readable groovy code there. Can you help out? We have a Slack going but there are only a few people :/ need more brains to solve this.

**Comment by dcmeglio** [comment]
I wouldn't mind helping but I've never worked in Python before, I've mainly been a .NET guy so I'll have somewhat of a learning curve. I was actually considering a different direction, I was going to replace the guts of the device with a rpi to control the sensors but I wouldn't mind trying both techniques out.

**Comment by tedder** [comment]
I'm using a rpi to hijack the API calls. The hardware seemed a little excessive for a pi (or esp32) brain replacement. It's a good excuse to run a PiHole locally :)

[email me](https://github.com/tedder/petnet-api-hacking#how-can-i-help); [the code](https://github.com/tedder/petnet-api-hacking/blob/master/feeder_api/responderapp.py) shouldn't be too overwhelming.

**Comment by kruton** [comment]
I implemented the pairing for the second generation in an Android app. It joins the network and immediately requests to api.arrowconnect.io currently.

**Comment by tedder** [comment]
does it work? or it works until hitting the API?

**Comment by kruton** [comment]
api.arrowconnect.io doesn't exist anymore (you just get NXDomain) and I haven't looked at how to set up the MITM proxy in this repo.

**Comment by kruton** [comment]
I set up a fake DNS entry for api.arrowconnect.io and mqtt-a01.arrowconnect.io and it's connecting to both.

It appears it wants to connect to port 8883 for MQTT which it's reading as an HTTP request when I forward it to `responderapp.py`. Do I need to set up some kind of MQTT to websockets connector to get that part to work?

```
  -> HTTP protocol error in client request: Bad HTTP request line: b'\x10\xa9\x01\x00\x04MQTT\x04\xc0\x00'
```
In the meantime, I just setup a mosquitto server to see what it would want to do. I'm not that familiar with the internals of MQTT, but here's what the log output:
```
1601876314: New client connected from 10.100.10.1 as 40285608b03f085d1b4e31ec5f60b3b912f64f2d (p2, c0, k10, u'/pegasus:40285608b03f085d1b4e31ec5f60b3b912f64f2d').
1601876314: No will message specified.
1601876314: Sending CONNACK to 40285608b03f085d1b4e31ec5f60b3b912f64f2d (0, 0)
1601876319: Received SUBSCRIBE from 40285608b03f085d1b4e31ec5f60b3b912f64f2d
1601876319: 	krs/cmd/stg/40285608b03f085d1b4e31ec5f60b3b912f64f2d (QoS 2)
1601876319: 40285608b03f085d1b4e31ec5f60b3b912f64f2d 2 krs/cmd/stg/40285608b03f085d1b4e31ec5f60b3b912f64f2d
1601876319: Sending SUBACK to 40285608b03f085d1b4e31ec5f60b3b912f64f2d
1601876320: Received SUBSCRIBE from 40285608b03f085d1b4e31ec5f60b3b912f64f2d
1601876320: 	krs/api/stg/40285608b03f085d1b4e31ec5f60b3b912f64f2d (QoS 2)
1601876320: 40285608b03f085d1b4e31ec5f60b3b912f64f2d 2 krs/api/stg/40285608b03f085d1b4e31ec5f60b3b912f64f2d
1601876320: Sending SUBACK to 40285608b03f085d1b4e31ec5f60b3b912f64f2d
1601876320: Received PUBLISH from 40285608b03f085d1b4e31ec5f60b3b912f64f2d (d0, q1, r0, m4, 'krs.tel.gts.40285608b03f085d1b4e31ec5f60b3b912f64f2d', ... (209 bytes))
1601876320: Sending PUBACK to 40285608b03f085d1b4e31ec5f60b3b912f64f2d (m4, rc0)
1601876320: Received PUBLISH from 40285608b03f085d1b4e31ec5f60b3b912f64f2d (d0, q1, r0, m5, 'krs.tel.gts.40285608b03f085d1b4e31ec5f60b3b912f64f2d', ... (177 bytes))
1601876320: Sending PUBACK to 40285608b03f085d1b4e31ec5f60b3b912f64f2d (m5, rc0)
```

**Comment by mbillow** [comment]
Closing this out since PetNet is _very_ dead at this point and I doubt we will get much more from RE'ing the app.
