### ISSUE TITLE
docker-compose up -d petnet-feeder-service

### ISSUE THREAD

**Issue by bob5731** [feedernet/petnet-feeder-service#70]
The Compose file is invalid because:
Service nginx has neither an image nor a build context specified. At least one must be provided.

**Comment by mbillow** [comment]
Did you read the comments in the compose file and choose an appropriate line to un-comment? 

Because we support older ARM architectures (like the Pi Zero W) you have to choose an nginx image based on what device you are running FeederNet on. 🙂

**Comment by bob5731** [comment]
So how do I get nginx image Pi 3b+?

**Comment by mbillow** [comment]
Just uncomment this line: https://github.com/feedernet/petnet-feeder-service/blob/f1009b04a82fee2579b4e639b0f6f47904f2d24f/sample/docker-compose.yaml#L43

**Comment by bob5731** [comment]
so delete the #?

**Comment by bob5731** [comment]
Can add fix to the Wiki?

**Comment by bob5731** [comment]
sudo docker-compose up -d
Pulling nginx (nginx:latest)...
latest: Pulling from library/nginx
b6e5ca4da968: Pull complete
2c34d682b95d: Pull complete
020f9e72113f: Pull complete
9adeb73e82df: Pull complete
b46304c62a09: Pull complete
9f6d60dc775c: Pull complete
Digest: sha256:097c3a0913d7e3a5b01b6c685a60c03632fc7a2b50bc8e35bcaa3691d788226e
Status: Downloaded newer image for nginx:latest
petnet-feeder-service is up-to-date
Creating nginx ... error

ERROR: for nginx  Cannot start service nginx: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/petnet-feeder-service/data/nginx.conf" to rootfs at "/etc/nginx/conf.d/default.conf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for nginx  Cannot start service nginx: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/root/petnet-feeder-service/data/nginx.conf" to rootfs at "/etc/nginx/conf.d/default.conf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

how do I fix it?

**Comment by mbillow** [comment]
You shouldn’t be running `docker-compose` as root with `sudo`. When you do that, it makes the `${HOME}` in the compost file resolve to root’s homedir, not yours. The setup instructions for Docker should include adding your user to the `docker` group so that you can use Docker without root access.

**Comment by mbillow** [comment]
Also, all of this is already in the Wiki. The instructions under step 4 include setting the right nginx image and altering the variables to suit your environment.

https://github.com/feedernet/petnet-feeder-service/wiki/Getting-Started#setting-up-your-first-instance

**Comment by bob5731** [comment]
Can get a copy of your pi image  with it running?

**Comment by bob5731** [comment]
I can not figure it out. So how do I fix?

**Comment by bob5731** [comment]
do you have any info on get v1 one work yet.

**Comment by bob5731** [comment]
I can get config work all. So do The Android  app to the my feeder config.

**Comment by mbillow** [comment]
The V1 feeders are based on a completely different IoT platform that actually enforces valid, trusted SSL certificates. It is fair to say that this project will likely never support them.

**Comment by mbillow** [comment]
You haven’t given any error messages or details to what is or isn’t working. Please make sure you are reading each step in the Wiki carefully. It was written as I setup a new device from scratch so it handles each step in detail without assumptions.

**Comment by bob5731** [comment]
The Android app keeps giving me a connection error?On Nov 20, 2021 9:26 PM, Marc Billow ***@***.***> wrote:

You haven’t given any error messages or details to what is or isn’t working. Please make sure you are reading each step in the Wiki carefully. It was written as I setup a new device from scratch so it handles each step in detail without assumptions.

**Comment by bob5731** [comment]
The Android app keeps giving me a error_wifi_found and error_wifi_conn and status_wif_found. how do I fix it?
read each step in the Wiki and have do each step in the Wiki.
I jest got a new v 2 feeder

**Comment by mbillow** [comment]
If I remember correctly from writing the iOS app, the feeder does spit out a few errors when switching to a new WiFi network. This might be expected. 

Have you checked to see if the feeder is connected to your network? Most home routers will list connected devices in their GUIs.

**Comment by bob5731** [comment]
Yes it did not connect to my home routers. The light is red.

**Comment by mbillow** [comment]
The light won’t change colors until the feeder connects to FeederNet, it will be red if it is connected to WiFi or not. You checked your router’s GUI and don’t see the feeder?

**Comment by bob5731** [comment]
npm start


./src/styles/index.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/styles/index.scss)
Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.

**Comment by mbillow** [comment]
I’m not sure I get what you are trying to do? Earlier in the thread you asked how to start the Docker image and now you are trying to run `npm`. The container image has a fully compiled version of the front end included, you don’t need `npm` to run it.

Regardless, I’m not sure an issue on a specific project is the right place to troubleshoot issues with languages or package managers. There is likely bountiful information about how to resolve this specific problem out on the internet.

**Comment by bob5731** [comment]
I'm trying to run you petnet-feeder-service using your steup.

**Comment by mbillow** [comment]
If you are going to be running it on a RPi, which you are based on the ARM architecture mentioned in the error, my suggestion is to use the Docker image.

**Comment by bob5731** [comment]
Ok then I will use the Docker image. But how do I get connect to my network so I can use it.

**Comment by mbillow** [comment]
Have you done the DNS redirection/hijacking and tested it?

**Comment by bob5731** [comment]
I do make a hosts file
Create a hosts file for dnsmasq in /etc/dnsmasq.hosts:
{IP of Device}   api.arrowconnect.io
{IP of Device}   mqtt-a01.arrowconnect.io

 systemctl status dnsmasq
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2021-11-28 18:08:14 GMT; 1h 57min ago
  Process: 503 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
  Process: 511 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 544 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
 Main PID: 543 (dnsmasq)
    Tasks: 1 (limit: 1935)
   CGroup: /system.slice/dnsmasq.service
           └─543 /usr/sbin/dnsmasq -x /run/dnsmasq/dnsmasq.pid -u dnsmasq -r /run/dnsmasq/resolv.conf -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anc

Nov 28 18:08:14 raspberrypi systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.
Nov 28 18:08:22 raspberrypi dnsmasq[543]: reading /run/dnsmasq/resolv.conf
Nov 28 18:08:22 raspberrypi dnsmasq[543]: using nameserver 192.168.50.1#53
Nov 28 18:08:22 raspberrypi dnsmasq[543]: using nameserver 8.8.8.8#53
Nov 28 18:08:22 raspberrypi dnsmasq[543]: using nameserver fd51:42f8:caae:d92e::1#53
Nov 28 18:08:23 raspberrypi dnsmasq[543]: reading /run/dnsmasq/resolv.conf
Nov 28 18:08:23 raspberrypi dnsmasq[543]: using nameserver 192.168.50.1#53
Nov 28 18:08:23 raspberrypi dnsmasq[543]: using nameserver 8.8.8.8#53
Nov 28 18:08:23 raspberrypi dnsmasq[543]: using nameserver fd51:42f8:caae:d92e::1#53
Nov 28 18:08:23 raspberrypi dnsmasq[543]: using nameserver 192.168.50.78#53

**Comment by mbillow** [comment]
Have you set your router to hand out your dnsmasq server’s IP as the DNS server for the network?

**Comment by bob5731** [comment]
Yes I did. By using WAN - Virtual Server / Port Forwarding.

![petnet r](https://user-images.githubusercontent.com/16548974/143784604-b71ea4f9-e884-42f0-8def-b5d0a252d3ba.png)

**Comment by bob5731** [comment]
would be called qca-ioeboard. If so the yes . But it will not stay connected

**Comment by mbillow** [comment]
Yes, qca-ioeboard is the feeder. It is disconnecting and reconnecting because it can’t reach FeederNet. You don’t need to do port forwarding to get this to work, you need to adjust your DHCP settings to hand out the IP address of the device running dnsmasq as the DNS server. 

**Note:** You likely want to do this on a separate network (or VLAN), if possible, unless you can guarantee uptime on your DNS server.

**Comment by bob5731** [comment]
would rip be ip for the /etc/dnsmasq.hosts?

**Comment by mbillow** [comment]
Yup

**Comment by bob5731** [comment]
Thank You I will let you know If I get working. I'm at het New Feeder Wizard.
